#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, sys, math, zlib


def checksum_compute(obj):
    """Compute CRC32 over canonical JSON (no cksum field). obj must not contain 'cksum'."""
    canonical = json.dumps(obj, sort_keys=True)
    return zlib.crc32(canonical.encode()) & 0xffffffff


def checksum_verify(obj):
    """Return True if obj has valid 'cksum' matching recomputed checksum."""
    if "cksum" not in obj or not isinstance(obj.get("cksum"), (int, float)):
        return False
    received = int(obj["cksum"]) & 0xffffffff
    copy = dict(obj)
    del copy["cksum"]
    expected = checksum_compute(copy)
    return received == expected


class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None
        self.next_expected = 0
        self.buffer = {}  # seq -> data

    def send(self, message):
        self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        try:
            parsed = json.loads(data.decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            return None  # Corrupted packet, drop
        self.log("Received message %s" % data.decode("utf-8", errors="replace"))
        return parsed

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                msg = self.recv(conn)
                if msg is None:
                    continue
                if "seq" not in msg or "data" not in msg:
                    continue
                if not checksum_verify(msg):
                    continue  # Corrupted data packet, drop (do not ACK)
                seq = int(msg["seq"])
                ack_msg = {"type": "ack", "seq": msg["seq"]}
                ack_msg["cksum"] = checksum_compute(ack_msg)
                if seq < self.next_expected:
                    # Duplicate: ACK so sender can clear, do not print
                    self.send(ack_msg)
                else:
                    # In-order or out-of-order: store and drain in order
                    self.buffer[seq] = msg["data"]
                    while self.next_expected in self.buffer:
                        sys.stdout.write(self.buffer[self.next_expected])
                        sys.stdout.flush()
                        del self.buffer[self.next_expected]
                        self.next_expected += 1
                    self.send(ack_msg)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()