#!/usr/bin/env python3
import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375

class Sender:
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.remote_host = None
        self.remote_port = None

        self.window_size = 2
        self.unacked = {}
        self.msg = None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data)
            return json.loads(data.decode("utf-8"))

    def run(self):
        seq = 0
        timeout_interval = 1.0
        eof_reached = False 

        while True:
            sockets = [self.socket]
            # Listen to stdin for incoming acks from reciver
            if len(self.unacked) < self.window_size and not eof_reached:
                sockets.append(sys.stdin)

            socks = select.select(sockets, [], [], 0.1)[0]

            # Seeing if any acks take longer then 1 second, consider them lost and resend
            current_time = time.time()
            for s, packet_info in self.unacked.items():
                if((current_time - packet_info["time"]) > timeout_interval):
                    self.log("Timeout expired; resending packet")
                    self.send(packet_info["msg"])
                    packet_info["time"] = current_time

            for conn in socks:
                # looking at incoming acks and deleting them from mem to slide window
                if conn == self.socket:
                    data = self.recv(conn)

                    if data:
                        if data["type"] == "ack" and data["seq"] in self.unacked:
                            del self.unacked[data["seq"]]

                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0: 
                        eof_reached = True
                        continue
                    
                    self.msg = {"type": "data", "seq": seq, "data": data}
                    self.send(self.msg)


                    self.unacked[seq] = {"msg": self.msg, "time": time.time()}
                    seq += 1


            if eof_reached and len(self.unacked) == 0:
                self.log("All done")
                sys.exit(0)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()