#!/usr/bin/env python3
import argparse, socket, time, json, select, struct, sys, math, zlib

DATA_SIZE = 1375


def checksum_compute(obj):
    """Compute CRC32 over canonical JSON (no cksum field). obj must not contain 'cksum'."""
    canonical = json.dumps(obj, sort_keys=True)
    return zlib.crc32(canonical.encode()) & 0xffffffff


def checksum_verify(obj):
    """Return True if obj has valid 'cksum' matching recomputed checksum."""
    if "cksum" not in obj or not isinstance(obj.get("cksum"), (int, float)):
        return False
    received = int(obj["cksum"]) & 0xffffffff
    copy = dict(obj)
    del copy["cksum"]
    expected = checksum_compute(copy)
    return received == expected

class Sender:
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.remote_host = None
        self.remote_port = None

        self.window_size = 2
        self.unacked = {}
        self.msg = None

        self.wobble = 0.0
        self.estimated_rtt = 1.0
        self.highest_ack = -1

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        try:
            parsed = json.loads(data.decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            return None  # Corrupted packet, drop
        self.log("Received message %s" % data)
        if not checksum_verify(parsed):
            return None  # Bad checksum, drop
        return parsed

    def run(self):
        seq = 0
        eof_reached = False 
        timeout_interval = 2.0

        while True:
            sockets = [self.socket]
            # Listen to stdin for incoming acks from reciver
            if len(self.unacked) < self.window_size and not eof_reached:
                sockets.append(sys.stdin)

            socks = select.select(sockets, [], [], 0.1)[0]

            # Seeing if any acks take longer then 1 second, consider them lost and resend
            current_time = time.time()
            for s, packet_info in self.unacked.items():
                if((current_time - packet_info["time"]) > timeout_interval):
                    self.log("Timeout expired; resending packet")
                    self.send(packet_info["msg"])
                    packet_info["time"] = current_time
                    packet_info["retransmitted"] = True
                    self.window_size = max(2, self.window_size // 2)

            for conn in socks:
                # looking at incoming acks and deleting them from mem to slide window
                if conn == self.socket:
                    data = self.recv(conn)

                    if data:
                        if data["type"] == "ack":
                            ack_seq = int(data["seq"])

                            if ack_seq > self.highest_ack:
                                self.highest_ack = ack_seq

                            if ack_seq in self.unacked:
                                packet_info = self.unacked[ack_seq]

                                if packet_info["retransmitted"] == False:
                                    timeout_interval = self.update_timeout(packet_info["time"], time.time())
                                    timeout_interval = max(0.5, timeout_interval)
                                    self.window_size += 1

                                del self.unacked[ack_seq]

                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0: 
                        eof_reached = True
                        continue
                    
                    self.msg = {"type": "data", "seq": seq, "data": data}
                    self.msg["cksum"] = checksum_compute(self.msg)
                    self.send(self.msg)


                    self.unacked[seq] = {"msg": self.msg, "time": time.time(), "retransmitted": False}
                    seq += 1


            if eof_reached and len(self.unacked) == 0:
                self.log("All done")
                sys.exit(0)

    def update_timeout(self, send_time, ack_time):
            sample_rtt = ack_time - send_time
            
            self.estimated_rtt = 0.875 * self.estimated_rtt + 0.125 * sample_rtt
            
            dev_rtt = abs(sample_rtt - self.estimated_rtt)
            
            self.wobble = 0.75 * self.wobble + 0.25 * dev_rtt
            
            timeout_interval = self.estimated_rtt + 4 * self.wobble
            return timeout_interval




if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()